# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Mmmm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mmmm

end

target 'MmmmKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MmmmKit

end
